In [3]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import timeit

sns.set_style("ticks")
%matplotlib inline
%load_ext lab_black

In [58]:
np.random.seed(100)

n_iters = 10 ** 5
# number of repetitinos per simulation
bins_n = 7
# number of bins wanted in histogram


# model parameters:

num_rooms = 100
# number of rooms
rental_rate = 250
# daily rental rate
variable_cost = 60
# variable cost for room

no_show_p = 0.05
# probability a guest makes a reservation but doesn't show up
cost_overbooked = 400
# cost for accomndating overbooked rooms

num_reserve = np.arange(95, 101)
# the number of reservations taken to be considered in simulation eg from 98 reservations to 110 reservations

### Calculation

In [54]:
start = timeit.default_timer()
# start execution timer


num_arrivals = np.array(
    [
        [np.random.binomial(j, (1 - no_show_p)) for i in range(n_iters)]
        for j in num_reserve
    ]
)
print(num_arrivals.shape)
print(num_arrivals)
num_staying = np.minimum(num_arrivals, num_rooms)
print(num_staying.shape)

"""
    # returns the number of people stayin
    num_overbooked = np.maximum(0, num_arrivals - num_rooms)
    # returns the number of overbooked rooms
    daily_profit = (
        rental_rate * j - variable_cost * num_staying - cost_overbooked * num_overbooked
    )
    # daily profit
    avg_profit = np.average(daily_profit)
    # returns the average daily profit per simulation
    print(f"Number of Reservation : {j} Average Profit: ${avg_profit:.2f}")

"""

stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)
# print(num_arrivals_2)

(6, 10000)
[[90 92 91 ... 91 94 93]
 [89 85 88 ... 90 88 93]
 [90 91 93 ... 91 91 92]
 [92 95 91 ... 93 95 93]
 [96 93 95 ... 94 97 91]
 [96 95 97 ... 95 95 93]]
(6, 10000)
Execution Time:  0.188564299999598


In [32]:
start = timeit.default_timer()
# start execution timer


num_arrivals_2 = np.array([np.random.binomial(95, (1 - no_show_p)) for i in range(n_iters) ])
num_arrivals_2 = np.array([np.random.binomial(96, (1 - no_show_p)) for i in range(n_iters) ])
num_arrivals_2 = np.array([np.random.binomial(97, (1 - no_show_p)) for i in range(n_iters) ])
num_arrivals_2 = np.array([np.random.binomial(98, (1 - no_show_p)) for i in range(n_iters) ])
num_arrivals_2 = np.array([np.random.binomial(99, (1 - no_show_p)) for i in range(n_iters) ])
num_arrivals_2 = np.array([np.random.binomial(100, (1 - no_show_p)) for i in range(n_iters) ])




print(num_arrivals_2.shape)

    
stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)
# print(num_arrivals_2)


(100000,)
Execution Time:  4.763183599999934


In [29]:
start = timeit.default_timer()
# start execution timer


for j in num_reserve:
    num_arrivals = np.array([np.random.binomial(j, (1 - no_show_p)) for i in range(n_iters)])
#     print(type(num_arrivals))
print(num_arrivals_2.shape)

stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)
# print(num_arrivals_2)

(100000,)
Execution Time:  4.7923046000000795


In [5]:
start = timeit.default_timer()
for j in num_reserve:
    arr_iters = np.ones(n_iters) * j
    # initialize number of arrivals array
    num_arrivals = []
    for i in arr_iters:
        num_arrivals.append(np.random.binomial(i, (1 - no_show_p), size=None))
stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)

Execution Time:  0.44794849999999986


### Original

In [24]:
start = timeit.default_timer()
# start execution timer

for j in num_reserve:
    arr_iters = np.ones(n_iters) * j
    # initialize number of arrivals array
    num_arrivals = []
    for i in arr_iters:
        num_arrivals.append(np.random.binomial(i, (1 - no_show_p), size=None))
    # returns the number of arrivals
    num_arrivals = np.array(num_arrivals)
    # transform the number of arrivals into an numpy array
    num_staying = np.minimum(num_arrivals, num_rooms)
    # returns the number of people stayin
    num_overbooked = np.maximum(0, num_arrivals - num_rooms)
    # returns the number of overbooked rooms
    daily_profit = (
        rental_rate * j - variable_cost * num_staying - cost_overbooked * num_overbooked
    )
    # daily profit
    avg_profit = np.average(daily_profit)
    # returns the average daily profit per simulation
    print(f"Number of Reservation : {j} Average Profit: ${avg_profit:.2f}")


stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)

Number of Reservation : 95 Average Profit: $18335.19
Number of Reservation : 96 Average Profit: $18528.28
Number of Reservation : 97 Average Profit: $18721.55
Number of Reservation : 98 Average Profit: $18914.15
Number of Reservation : 99 Average Profit: $19106.44
Number of Reservation : 100 Average Profit: $19299.93
Number of Reservation : 101 Average Profit: $19490.34
Number of Reservation : 102 Average Profit: $19671.97
Number of Reservation : 103 Average Profit: $19831.19
Number of Reservation : 104 Average Profit: $19945.29
Number of Reservation : 105 Average Profit: $20010.61
Number of Reservation : 106 Average Profit: $20015.56
Number of Reservation : 107 Average Profit: $19978.06
Number of Reservation : 108 Average Profit: $19907.27
Number of Reservation : 109 Average Profit: $19797.77
Number of Reservation : 110 Average Profit: $19691.62
Execution Time:  14.767758299999969


### Vectorized

In [64]:
start = timeit.default_timer()
# start execution timer

# num_arrivals = np.array(num_arrivals)
# transform the number of arrivals into an numpy array
num_staying = np.minimum(num_arrivals, num_rooms)
# returns the number of people stayin
num_overbooked = np.maximum(0, num_arrivals - num_rooms)

# print(rental_rate.dot(num_reserve))
# returns the number of overbooked rooms
# daily_profit = (
#     rental_rate * num_reserve - variable_cost * num_staying - cost_overbooked * num_overbooked
# )

daily_profit = (
    num_reserve.dot(rental_rate)[:, None]
    - variable_cost * num_staying
    - cost_overbooked * num_overbooked
)
# temp = variable_cost * num_staying.
print("daily rate", (num_reserve * (rental_rate))[:, None])
print((num_reserve * (rental_rate))[:, None].shape)
print("hi", num_reserve.dot(rental_rate)[:, None] - variable_cost * num_staying)
print(daily_profit)
print(daily_profit.shape)
# daily profit
avg_profit = np.average(daily_profit, axis=1)
# returns the average daily profit per simulation
# for i,j in num_reserve,avg_profit:
for i, j in zip(num_reserve, avg_profit):
    print(f"Number of Reservation : {i} Average Profit: ${j}")


stop = timeit.default_timer()
# stop execution timer
print("Execution Time: ", stop - start)

daily rate [[23750]
 [24000]
 [24250]
 [24500]
 [24750]
 [25000]]
(6, 1)
hi [[18350 18230 18290 ... 18290 18110 18170]
 [18660 18900 18720 ... 18600 18720 18420]
 [18850 18790 18670 ... 18790 18790 18730]
 [18980 18800 19040 ... 18920 18800 18920]
 [18990 19170 19050 ... 19110 18930 19290]
 [19240 19300 19180 ... 19300 19300 19420]]
[[18350 18230 18290 ... 18290 18110 18170]
 [18660 18900 18720 ... 18600 18720 18420]
 [18850 18790 18670 ... 18790 18790 18730]
 [18980 18800 19040 ... 18920 18800 18920]
 [18990 19170 19050 ... 19110 18930 19290]
 [19240 19300 19180 ... 19300 19300 19420]]
(6, 10000)
Number of Reservation : 95 Average Profit: $18334.43
Number of Reservation : 96 Average Profit: $18528.552
Number of Reservation : 97 Average Profit: $18721.444
Number of Reservation : 98 Average Profit: $18912.068
Number of Reservation : 99 Average Profit: $19107.306
Number of Reservation : 100 Average Profit: $19301.47
Execution Time:  0.005020999999942433


# search on list comprehension with numpy arrays
# 2 finish vector based code without ones function
# 3 modify vector to matrix; and you need to add axis for finding min number staying profit etc etc 
# compare item 2 and 3 time performance